config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get '/search', to: 'words#search', as: 'search'
  resources :words, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :kanjis, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :jlpts, only: [:index, :edit, :destroy]
  resources :word_types, only: [:edit, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jlpt.rb
class Jlpt < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :kanjis, dependent: :destroy
end

app/models/kanji.rb
class Kanji < ApplicationRecord
  belongs_to :jlpt
  validates :title, :pt, :strike, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :word_type
  belongs_to :jlpt
  validates :romaji, :pt, :kana, presence: true
end

app/models/word_type.rb
class WordType < ApplicationRecord
  has_many :words, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :user_parameters, if: :devise_controller?

  protected

  def user_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/jlpts_controller.rb
class JlptsController < ApplicationController
  def index
    @jlpts = Jlpt.all
    @word_types = WordType.all
  end

  def destroy
    @jlpt = Jlpt.find(params[:id])
    @jlpt.destroy
  
    redirect_to jlpts_path, notice: 'Apagado com sucesso'
  end

  def edit; end
end

app/controllers/kanjis_controller.rb
class KanjisController < ApplicationController
  def index
    @kanjis = Kanji.all
  end

  def show
    @kanji = Kanji.find(params[:id])
  end

  def new
    @kanji = Kanji.new
  end

  def create 
    @kanji = Kanji.new(kanji_params)
    if @kanji.save
      redirect_to @kanji, notice: 'Adicionado com sucesso'
    else
      flash[:alert] = 'Não pode ser enviada'
      render :new
    end
  end

  def edit 
    @kanji = Kanji.find(params[:id])
  end

  def update
    @kanji = Kanji.find(params[:id])
    if @kanji.update(kanji_params)
      redirect_to @kanji, notice: 'Editado com sucesso'
    else
      flash[:alert] = 'Não pode ser enviada'
      render :new
    end
  end

  def destroy
    @kanji = Kanji.find(params[:id])
    @kanji.destroy
  
    redirect_to kanjis_path, notice: 'Apagado com sucesso'
  end

  private

  def kanji_params
    params.require(:kanji)
          .permit(:title, :radical, :most_used, :strike, :kun, :eg, :jlpt_id,
                  :pt, :onyomi)
  end

end

app/controllers/word_types_controller.rb
class WordTypesController < ApplicationController
  def destroy
    @word_type = WordType.find(params[:id])
    @word_type.destroy
  
    redirect_to jlpts_path, notice: 'Apagado com sucesso'
  end

  def edit; end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :create, :update]

  def search
    @words = WordService.search(search_query)
    @kanjis = KanjiService.search(search_query)
    return unless(@words.empty? && @kanjis.empty?)
    flash[:error] = 'Não foi encontrado nada'
    redirect_to root_path
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to @word, notice: 'Adicionado com sucesso'
    else
      flash[:alert] = 'Não pode ser enviada'
      render :new
    end
  end

  def index
    @words = Word.all
  end

  def edit 
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      redirect_to @word, notice: 'Editado com sucesso'
    else
      flash[:alert] = 'Não pode ser enviada'
      render :new
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
  
    redirect_to words_path, notice: 'Apagado com sucesso'
  end

  private

  def search_query
    params[:query]
  end

  def word_params
    params.require(:word)
          .permit(:romaji, :pt, :kana, :kanji, :obs, :word_type_id, :jlpt_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class='container'>
  <h2><%= flash[:error] %></h2>
  <h1>Dicionario JP- PT do mavmaso</h1>

  Jishobr é um dicionario de português-japonês .

Alguns exemplos do que você pode procurar aqui:
<ul>
  <li>Somente algumas palavras ja foram adicionadas tais como:</li>
  <ul>
    <li>tatoeba, たとえば, 例えば</li>
    <li>omiyage, おみやげ, お土産</li>
    <li>au, あう, 会う</li>
    <li>etc</li>
  </ul>
  <li>Jishobr e um dicionario tanto de palavras como de kanji, procure por exemplo, 例, e veja o resultado</li>
  <li> Ainda estamos trabalhando para entregar mais funcoes no Jishobr </li>
</ul>

Logo teremos mais funções por aqui, não deixa de visitar tambem <a href="http://skdesu.com" target="_blank">skdesu.com</a>

</div>

app/views/jlpts/index.html.erb
<div class='container'>
  <div class="row">
    <div class="col-sm">
    <% @jlpts.each do |jlpt| %>
      <div class='col-sm' id="<%= "#{jlpt.title}"%>">
        <h2><%= link_to(jlpt.title,edit_jlpt_path(jlpt)) %></h2>
        <p> ID: <%= jlpt.id %> </p>
        <% if current_user.admin? %>
          <%= link_to 'Editar', edit_jlpt_path(jlpt) %>
          <%= link_to 'Apagar', jlpt_path(jlpt), method: :delete %>
        <% end %>
        <hr>
      </div>
    <% end %>
    </div>
    <div class="col-sm">
    <% @word_types.each do |word_type| %>
      <div class='col-sm' id="<%= "#{word_type.title}"%>">
        <h2><%= link_to(word_type.title,edit_word_type_path(word_type)) %></h2>
        <p> ID: <%= word_type.id %> </p>
        <p> Subtipo: <%= word_type.sub_type %> </p>
        <% if current_user.admin? %>
          <%= link_to 'Editar', edit_word_type_path(word_type) %>
          <%= link_to 'Apagar', word_type_path(word_type), method: :delete %>
        <% end %>
        <hr>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/kanjis/edit.html.erb
<div style="width:800px; margin:0 auto;">
<h1>Editar Kanji no Jisho</h1>
<%= simple_form_for(@kanji) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: 'Kanji' %>
  <%= f.input :onyomi, label: 'On' %>
  <%= f.input :kun %>
  <%= f.input :pt, label: 'Sentido' %>
  <%= f.input :most_used, label: 'Mais usados' %>
  <%= f.input :radical %>
  <%= f.input :strike, label: 'Tracos' %>
  <%= f.input :eg, label: 'Exemplos de uso' %>
  <%= f.label :jlpt_id, 'JLPT' %>
  <%= f.collection_select(:jlpt_id , Jlpt.all, :id , :title) %>
  <br>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/kanjis/index.html.erb
<div class='container'>
  <br>
  <% @kanjis.each do |kanji| %>
  <div id="<%= "#{kanji.title}"%>">
    <h2><%= link_to(kanji.title,edit_kanji_path(kanji)) %></h2>
    <p> Sentido: <%= kanji.pt %></p>
    <ul>
      <li>On:  <%= kanji.onyomi %></li>
      <li>Kun: <%= kanji.kun %></li>
      <li>JLPT:  <%= kanji.jlpt.title %></li>
    </ul>
    <br>
    <% if current_user.admin? %>
      <%= link_to 'Editar', edit_kanji_path(kanji) %>
      <%= link_to 'Apagar', kanji_path(kanji), method: :delete %>
    <% end %>
  </div>
  <hr>
  <% end %>
</div>

app/views/kanjis/new.html.erb
<div style="width:800px; margin:0 auto;">
<h1>Adicionar Novo Kanji ao Jisho</h1>
<%= simple_form_for(@kanji) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: 'Kanji' %>
  <%= f.input :onyomi, label: 'On' %>
  <%= f.input :kun %>
  <%= f.input :pt, label: 'Sentido' %>
  <%= f.input :most_used, label: 'Mais usados' %>
  <%= f.input :radical %>
  <%= f.input :strike, label: 'Tracos' %>
  <%= f.input :eg, label: 'Exemplos de uso' %>
  <%= f.label :jlpt_id, 'JLPT' %>
  <%= f.collection_select(:jlpt_id , Jlpt.all, :id , :title) %>
  <br>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>
<br>
<br>
</div>

app/views/kanjis/show.html.erb
<div class='container'>
<br>
  <h2><%= @kanji.title %></h2>
  <p> Sentido: <%= @kanji.pt %></p>
  <ul>
    <li>On: <%= @kanji.onyomi %></li>
    <li>Kun: <%= @kanji.kun %></li>
    <li>Tracos: <%= @kanji.strike %></li>
    <li>JLPT: <%= @kanji.jlpt.title %></li>
    <li>Nivel de uso: <%= @kanji.most_used %></li>
    <li>Radical: <%= @kanji.radical %></li>
  </ul>
  Exemplos: <%= @kanji.eg %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jishobr:Dicionario de Japones</title>
    <meta name="description" content="Jishobr - Seu Jisho em Portugues">
    <meta name="keywords" content=" dicionario, japones, portugues, japonês, português, jisho ">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/nav_bar' %>
    <%= render partial: 'shared/nav2' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
  <footer>
    <div class ="a">
      <a class="navbar-brand" href="https://github.com/mavmaso" target="_blank">Feito por mavmaso ver.09.23</a>
    </div>
  </footer>
</html>

app/views/shared/_nav2.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <a class="navbar-brand" href="#">Menu de Usuario</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" href="#">ADMIN</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Palavras', new_word_path, class: 'nav-link' %></li>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Kanji', new_kanji_path, class: 'nav-link' %></li>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Editar
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Palavras', words_path, class: 'dropdown-item' %>
            <%= link_to 'Kanji', kanjis_path, class: 'dropdown-item' %>
            <%= link_to 'JLPT-etc', jlpts_path, class: 'dropdown-item' %>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="#">Usuario: <%= current_user.email %></a>
        </li>

        <li class="nav-item">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Entrar', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>"><h1 class="logo">JishoBR</h1></a>
  <section class="pesquisa">
    <%= form_tag(search_path, method: "get") do %>
      <div class='container'>
        <div class="row justify-content-md-center">
          <div class="col-sm-2">
            <%= label_tag :query, "Pesquise" %>
          </div>
          <div class="col">
            <%= text_field_tag :query, nil, placeholder: 'romaji, kana, kanji, portugues', class: 'form-control' %>
          </div>
          <div class="col-sm-2">
            <%= submit_tag "Buscar", class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </section>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto lista">
      <li class="nav-item">
      </li>
    </ul>
  </div>
</nav>

app/views/words/edit.html.erb
<div style="width:800px; margin:0 auto;">
<h1>Editar Palavra no Jisho</h1>
<%= simple_form_for(@word) do |f| %>
  <%= f.error_notification %>
  <%= f.input :romaji %>
  <%= f.input :pt %>
  <%= f.input :kana %>
  <%= f.input :kanji %>
  <%= f.input :obs, label: 'Observacoes' %>
  <%= f.label :word_type_id, 'Tipo' %>
  <%= f.collection_select(:word_type_id , WordType.all, :id , :title) %>
  <%= f.label :jlpt_id, 'JLPT' %>
  <%= f.collection_select(:jlpt_id , Jlpt.all, :id , :title) %>
  <br>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>
<br>
<br>
</div>

app/views/words/index.html.erb
<div class='container'>
  <br>
  
  <% @words.each do |word| %>
  <div id="<%= "word-#{word.romaji}"%>">
    <h2><%= link_to(word.romaji,edit_word_path(word)) %></h2>
    <p> Tradução: <%= word.pt %></p>
    <ul>
      <li>Tipo:  <%= word.word_type.title %></li>
      <li>Kana:  <%= word.kana %></li>
      <li>Kanji: <%= word.kanji %></li>
      <li>JLPT:  <%= word.jlpt.title %></li>
    </ul>
    Observações: <%= word.obs %>
    <br>
    <% if current_user.admin? %>
      <%= link_to 'Editar', edit_word_path(word) %>
      <%= link_to 'Apagar', word_path(word), method: :delete %>
    <% end %>
    <hr>
  </div>
  <% end %>

</div>

app/views/words/new.html.erb
<div style="width:800px; margin:0 auto;">
<h1>Adicionar Nova Palavra ao Jisho</h1>
<%= simple_form_for(@word) do |f| %>
  <%= f.error_notification %>
  <%= f.input :romaji %>
  <%= f.input :pt %>
  <%= f.input :kana %>
  <%= f.input :kanji %>
  <%= f.input :obs, label: 'Observacoes' %>
  <%= f.label :word_type_id, 'Tipo' %>
  <%= f.collection_select(:word_type_id , WordType.all, :id , :title) %>
  <%= f.label :jlpt_id, 'JLPT' %>
  <%= f.collection_select(:jlpt_id , Jlpt.all, :id , :title) %>
  <br>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>
<br>
<br>
</div>

app/views/words/search.html.erb
<div class='container'>
  <div class="row">
    <div class="col-sm">
      <h3>Resultados da pesquisa em palavras</h3>
      <% @words.each do |word| %>
      <h2><%= link_to(word.romaji,word) %></h2>
      <p> Tradução: <%= word.pt %></p>
      <ul>
        <li>Tipo:  <%= word.word_type.title %></li>
        <li>Kana:  <%= word.kana %></li>
        <li>Kanji: <%= word.kanji %></li>
        <li>JLPT:  <%= word.jlpt.title %></li>
      </ul>
      Observações: <%= word.obs %>
      <br>
      <hr>
      <% end %>
    </div>
    <div class='col-sm'>
      <h3>Resultados da pesquisa de Kanjis</h3>
      <% @kanjis.each do |kanji| %>
      <h2><%= link_to(kanji.title,kanji) %></h2>
      <p> Sentido: <%= kanji.pt %></p>
      <ul>
        <li>On:  <%= kanji.onyomi %></li>
        <li>Kun: <%= kanji.kun %></li>
        <li>JLPT:  <%= kanji.jlpt.title %></li>
      </ul>
      <br>
      <hr>
      <% end %>
    <div>
  </div>
</div>

app/views/words/show.html.erb
<div class='container'>
  <h2><%= @word.romaji %></h2>
  <p> Tradução: <%= @word.pt %></p>
  <ul>
    <li>Tipo: <%= @word.word_type.title %></li>
    <li>Kana: <%= @word.kana %></li>
    <li>Kanji: <%= @word.kanji %></li>
    <li>JLPT: <%= @word.jlpt.title %></li>
  </ul>
  Observações: <%= @word.obs %>
</div>